[package]
name = "lobste-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
color-eyre = "0.6"
tui = "0.19"
crossterm = "0.25"
open = "4.1.0"
